# Complete task definition
- name: Install Docker SDK for Python
  # Add necessary lines here

- name: Copy docker directory
  ansible.builtin.copy:
  # Add necessary lines here

- name: Copy app.py.j2 template
  ansible.builtin.template:
  # Add necessary lines here
 
- name: Copy nginx.conf template
  ansible.builtin.template:
  # Add necessary lines here

- name: Build Docker images from Dockerfiles
  community.docker.docker_image:
    name: "{{ item.name }}"
    source: XXX
    build:
      path: "XXX"
      pull: XXX
    state: XXX
    force_source: yes
  loop:
    - { name: "{{ webapp_img }}", directory: webapp }
    - { name: "{{ db_img }}", directory: db }
    - { name: "{{ nginx_img }}", directory: nginx }

- name: Create network
  community.docker.docker_network:
  # Add necessary lines here

- name: Run MySQL container
  community.docker.docker_container:
    image: "XXX"
    name: "XXX"
    state: XXX
    restart: yes
    networks:
      - name: "XXX"
    networks_cli_compatible: XXX

- name: Run Flask container
  community.docker.docker_container:
    image: "XXX"
    name: "XXX"
    state: XXX
    restart: yes
    networks:
      - name: "XXX"
    networks_cli_compatible: XXX

- name: Run Nginx container
  community.docker.docker_container:
    image: "XXX"
    name: "XXX"
    state: XXX
    restart: yes
    published_ports: "XXX"
    networks:
      - name: "XXX"
    networks_cli_compatible: XXX

